import { useState } from 'react';

export default function Report() {
  const [downloadMessage, setDownloadMessage] = useState('');

  const reportContent = () => {
    const insights = ['Strong savings habit', 'Consistent bill payments', 'High spending on food'];
    const suggestions = [
      'Maintain low credit utilization under 30%',
      'Keep paying bills on time with auto-pay setup',
      'Reduce food & entertainment spending by 10%'
    ];

    return `AI Credit Score Report\n\n` +
      `Date: ${new Date().toLocaleDateString()}\n` +
      `Credit Score: 712 (Low Risk)\n\n` +
      `Analysis:\n` +
      '- Credit utilization is healthy but can be further optimized\n' +
      '- Payment history is strong, showing 8 months no late payments\n' +
      `- Risk signals from high dining/spending are mild\n\n` +
      `Insights:\n` +
      insights.map((text, idx) => `${idx + 1}. ${text}`).join('\n') +
      `\n\nSuggestions:\n` +
      suggestions.map((text, idx) => `${idx + 1}. ${text}`).join('\n') +
      `\n\nGenerated by AI Credit Score Platform`;
  };

  const handleDownload = () => {
    const blob = new Blob([reportContent()], { type: 'text/plain;charset=utf-8' });
    const href = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = href;
    a.download = `ai-credit-report-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(href);
    setDownloadMessage('Report downloaded successfully!');
  };

  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold">Report</h2>
      <div className="bg-card rounded-2xl p-6 shadow-lg">
        <h3 className="font-semibold mb-2">Monthly Credit Score Report</h3>
        <p className="text-white/80 mb-4">
          Your credit score is in the low-risk band with good payment behavior. Keep tracking your monthly savings and usage.
        </p>
        <button
          onClick={handleDownload}
          className="px-5 py-2.5 rounded-lg bg-neon text-black font-semibold hover:bg-neon/80 transition"
        >
          Download Report
        </button>
        {downloadMessage && <p className="text-green-300 mt-3">{downloadMessage}</p>}
      </div>
    </div>
  );
}

